GOOGLE_CLIENT_ID = "332483422044-c1msq62vilmk701kqb41p2k5k8irs9vk.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
FIREBASE_API_KEY = "AIzaSyCsLYefHbs30d-iOuS-bnGmTRsqg0asBS8"
